-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 07:24:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CONCESSIONARIAS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CONCESSIONARIAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CONCESSIONARIAS` DEFAULT CHARACTER SET utf8 ;
USE `CONCESSIONARIAS` ;

-- -----------------------------------------------------
-- Table `CONCESSIONARIAS`.`LOJAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONCESSIONARIAS`.`LOJAS` (
  `id_loja` INT NOT NULL AUTO_INCREMENT,
  `nome_loja` VARCHAR(45) NOT NULL,
  `endereco_loja` VARCHAR(100) NULL,
  PRIMARY KEY (`id_loja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONCESSIONARIAS`.`CARROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONCESSIONARIAS`.`CARROS` (
  `id_carro` INT NOT NULL AUTO_INCREMENT,
  `nome_carro` VARCHAR(45) NOT NULL,
  `ano_carro` YEAR(4) NULL,
  `cor_carro` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONCESSIONARIAS`.`MARCAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONCESSIONARIAS`.`MARCAS` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONCESSIONARIAS`.`CARROS_MARCAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONCESSIONARIAS`.`CARROS_MARCAS` (
  `id_carro_marca` INT NOT NULL AUTO_INCREMENT,
  `id_carro` INT NOT NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`id_carro_marca`),
  INDEX `id_carro_idx` (`id_carro` ASC) VISIBLE,
  INDEX `id_marca_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `id_carro`
    FOREIGN KEY (`id_carro`)
    REFERENCES `CONCESSIONARIAS`.`CARROS` (`id_carro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `CONCESSIONARIAS`.`MARCAS` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONCESSIONARIAS`.`CARROS_LOJAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONCESSIONARIAS`.`CARROS_LOJAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_carro` INT NOT NULL,
  `id_loja` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_carro_idx` (`id_carro` ASC, `id_loja` ASC) VISIBLE,
  INDEX `id_loja_idx` (`id_loja` ASC) VISIBLE,
  CONSTRAINT `id_carro`
    FOREIGN KEY (`id_carro` , `id_loja`)
    REFERENCES `CONCESSIONARIAS`.`CARROS` (`id_carro` , `id_carro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_loja`
    FOREIGN KEY (`id_loja`)
    REFERENCES `CONCESSIONARIAS`.`LOJAS` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
